[package]
name = "ftd2xx-sys"
description = "libftd2xx FFI bindings"
keywords = ["FTDI", "FFI", "bindings"]

license = "MIT"
authors = ["Nicolas Gabriel Cotti"]

version = "0.2.0"
edition = "2024"

readme = "README.md"
repository = "https://github.com/ncotti/ftd2xx-sys"

[features]
static = []
mpsse = []

[dependencies]

[build-dependencies]
bindgen = "0.71.0"
