# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026  Nicolas Gabriel Cotti

name: "Rust compiler, tester and documenter"
description: <
  Runs "cargo fmt", "cargo build", "cargo test" and "cargo doc",
  ensuring that the project compiles, all tests pass and there are no
  warnings in the generated documentation.
on: push

jobs:
  Rust_compiler:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: .
      RUST_PATH: .
      FTDI_VERSION: "1.4.35"
      FTDI_SRC_PATH: "vendor/linux-x86_64"
    steps:
      - name: "Checkout project repo"
        uses: actions/checkout@v5
        with:
          path: ${{ env.REPO_PATH }}

      - name: "Install libftd2xx"
        run: |
          tar -C "${{ env.REPO_PATH }}/vendor" -xzf "vendor/libftd2xx-linux-x86_64-${{ env.FTDI_VERSION }}.tgz"
          ./install_d2xx.sh ${{ env.REPO_PATH }}/${{ env.FTDI_SRC_PATH }} ${{ env.FTDI_VERSION }}

      - name: "Call cargo"
        uses: ncotti/cotti-ci/actions/rust@main
        with:
          target_dir: ${{ env.RUST_PATH }}
